[package]
edition = "2018"
authors = ["Jorge Aparicio <jorge@japaric.io>", "Dylan Frankland <dylan@frankland.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32F3 series microcontrollers"
keywords = ["arm", "cortex-m", "stm32f3xx", "hal"]
license = "0BSD"
name = "stm32f3xx-hal"
repository = "https://github.com/stm32-rs/stm32f3xx-hal"
documentation = "https://docs.rs/stm32f3xx-hal"
version = "0.3.0"

[package.metadata.docs.rs]
features = ["stm32f303", "rt"]

[dependencies]
cortex-m = ">=0.5.8,<0.7"
cortex-m-rt = "0.6.8"
embedded-hal = "0.2.3"
nb = "0.1.2"
stm32f3 = "0.8.0"

[dependencies.bare-metal]
version = "0.2.4"
features = ["const-fn"]

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.void]
default-features = false
version = "1.0.2"

[dev-dependencies]
cortex-m-semihosting = "0.3"
panic-halt = "0.2"


[features]
default = ["unproven"]
device-selected = []
rt = ["stm32f3/rt"]
stm32f301 = ["stm32f3/stm32f301", "device-selected"]
stm32f318 = ["stm32f3/stm32f3x8", "device-selected"]
stm32f302 = ["stm32f3/stm32f302", "device-selected"]
stm32f303 = ["stm32f3/stm32f303", "device-selected"]
stm32f373 = ["stm32f3/stm32f373", "device-selected"]
stm32f378 = ["stm32f3/stm32f3x8", "device-selected"]
stm32f334 = ["stm32f3/stm32f3x4", "device-selected"]
stm32f328 = ["stm32f3/stm32f3x8", "device-selected"]
stm32f358 = ["stm32f3/stm32f3x8", "device-selected"]
stm32f398 = ["stm32f3/stm32f3x8", "device-selected"]
unproven = ["embedded-hal/unproven"]

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
